=== Hazardius/HazVariousMaterials/STUDIA/2-semestr/Narzedzia-Informatyki/XML/students.xsd
<xs:schema
 xmlns:xs="http://www.w3.org/2001/XMLSchema">
 
	<xs:element name="students">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="student" maxOccurs="unbounded" type="studentType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
 
 	<xs:complexType name="studentType">
		<xs:sequence>
			<xs:element name="firstname" type="xs:string"/>
			<xs:element name="byear" type="xs:decimal"/>
			<xs:element name="dist" type="xs:decimal"/>										<xs:element name="boot" type="xs:decimal"/>
			<xs:element name="high" type="xs:decimal"/>
			<xs:element name="sex" type="xs:string"/>										<xs:element name="rose" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== Hazardius/HazVariousMaterials/STUDIA/2 semestr/Narz�dzia Informatyki/XML/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="students.xsl"?>
<students
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="students.xsd">
  <student>
	<firstname>Bartosz</firstname>
	<byear>1991</byear>
	<dist>0</dist>
	<boot>43</boot>
	<high>183</high>
	<sex>male</sex>
	<rose></rose>
  </student>
  <student>
	<firstname>Marcin</firstname>
	<byear>1990</byear>
	<dist>415</dist>
	<boot>43</boot>
	<high>183</high>
	<sex>male</sex>
	<rose>NE</rose>
  </student>
  <student>
	<firstname>Adrianna</firstname>
	<byear>1991</byear>
	<dist>100</dist>
	<boot>43</boot>
	<high>185</high>
	<sex>female</sex>
	<rose>N</rose>
  </student>
  <student>
	<firstname>Anna</firstname>
	<byear>1991</byear>
	<dist>50</dist>
	<boot>40</boot>
	<high>174</high>
	<sex>female</sex>
	<rose>S</rose>
  </student>
  <student>
	<firstname>Mikolaj</firstname>
	<byear>1991</byear>
	<dist>152</dist>
	<boot>42</boot>
	<high>172</high>
	<sex>male</sex>
	<rose>NE</rose>
  </student>
  <student>
	<firstname>Adam</firstname>
	<byear>1990</byear>
	<dist>220</dist>
	<boot>46</boot>
	<high>185</high>
	<sex>male</sex>
	<rose>NW</rose>
  </student>
  <student>
	<firstname>Adam</firstname>
	<byear>1991</byear>
	<dist>200</dist>
	<boot>45</boot>
	<high>176</high>
	<sex>male</sex>
	<rose>N</rose>
  </student>
  <student>
	<firstname>Magdalena</firstname>
	<byear>1991</byear>
	<dist>350</dist>
	<boot>38</boot>
	<high>162</high>
	<sex>female</sex>
	<rose>SE</rose>
  </student>
  <student>
	<firstname>Aneta</firstname>
	<byear>1991</byear>
	<dist>200</dist>
	<boot>37</boot>
	<high>157</high>
	<sex>female</sex>
	<rose>S</rose>
  </student>
  <student>
	<firstname>Milosz</firstname>
	<byear>1990</byear>
	<dist>120</dist>
	<boot>44</boot>
	<high>174</high>
	<sex>male</sex>
	<rose>SE</rose>
  </student>
  <student>
	<firstname>Piotr</firstname>
	<byear>1989</byear>
	<dist>0</dist>
	<boot>43</boot>
	<high>180</high>
	<sex>male</sex>
	<rose>N</rose>
  </student>
  <student>
	<firstname>Adam</firstname>
	<byear>1991</byear>
	<dist>0</dist>
	<boot>43</boot>
	<high>170</high>
	<sex>male</sex>
	<rose>N</rose>
  </student>
  <student>
	<firstname>Jakub</firstname>
	<byear>1991</byear>
	<dist>100</dist>
	<boot>43</boot>
	<high>179</high>
	<sex>male</sex>
	<rose>N</rose>
  </student>
  <student>
	<firstname>Maciej</firstname>
	<byear>1991</byear>
	<dist>126</dist>
	<boot>42</boot>
	<high>174</high>
	<sex>male</sex>
	<rose>N</rose>
  </student>
 </students>
